### ISSUE TITLE
Download flareplot

### ISSUE THREAD

**Issue by cgseitz** [GPCRviz/FlarePlot#13]
Hello,

After creating a flareplot, how can I download it for use in a presentation, or download a single image? I see the documentation on embedding it into a webpage, but I don't believe that is what I am looking for.

Best,
Christian

**Comment by RasmusFonseca** [comment]
Unfortunately we didn't get around to making this convenient in the flareplot page itself, only on the atlas page (where there's a download icon in the options menu). For a regular flareplot you can either screen-shot (mac Cmd-Shift-4) or the fancy version which is Right-click the flareplot, choose "Inspect", right click the "<svg ...>" element in the inspector and choose copy -> element. Go to a text-editor like notepad and paste the string. Save the file with a .svg ending. Illustrator and inkscape should be able to open up that file or you can convert it at https://svgtopng.com/. Hope that helps

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/8257515/176976691-6f47b0f0-6fb4-4d30-bb55-c2bf944fe5ee.png">

**Comment by cgseitz** [comment]
Hi Rasmus,

Thanks for telling me! I am using linux and mozilla. For those users to come across this, I had to upload my .json to atlas, then right click anywhere and select the "Inspector (Q)" mode, then in the <div id="flareDiv" ... click on the triangle to expand that, do it two more times until I see a "<svg width ..." single line, right click that, copy outer HTML, and paste that into a text file with vi or some text editor, saving it as an .svg as you mentioned. Uploading that to https://svgtopng.com/ then allows me to download the flare plot as a png. Woohoo!

Best,
Christian

**Comment by RasmusFonseca** [comment]
Excellent! I'll consider it a feature-request to get that download button copied over from the atlas 😆
